CREATE TABLE nba_macro_metrics_off (
  season_year VARCHAR(8),
  team_code VARCHAR(8),
  team_id BIGINT,
  game_date DATE,
  game_id VARCHAR(16),
  game_num SMALLINT,
  avg_fgm NUMERIC,
  avg_fga NUMERIC,
  avg_fg3m NUMERIC,
  avg_fg3a NUMERIC,
  avg_ast NUMERIC,
  avg_blk NUMERIC,
  avg_dreb NUMERIC,
  avg_oreb NUMERIC,
  avg_fta NUMERIC,
  avg_ftm NUMERIC,
  avg_pts NUMERIC,
  avg_reb NUMERIC,
  avg_stl NUMERIC,
  avg_tov NUMERIC
)